[book]
title = "Engineering Best Practices Guide"
authors = ["Engineering Community"]
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/your-org/best-practices"
git-repository-icon = "fa-github"